### ISSUE TITLE
It works?

### ISSUE THREAD

**Issue by carlosdelfresno** [jamesatgithub/GPrinterDroidBinding#1]
I see posts of you asking for information because the android binding for the printer didn't work (compile, but threw warnings saying that the class GpPrintService it couldn't be loaded.

Did you finally fix this? If it worked, could you post the android project for using this?

Thanks!!

**Comment by jzhouw** [comment]
it should work, but I cannot post the android source project here. one important note is Gprinter relies on a android AIDL, so you need some extra steps (e.g. use Android Studio to compile the .java to a .jar) to get it working besides the binding project in this repo.

here's steps:
1. VS (Xamarin) : follow the normal binding step e.g. add the target sdk .jar with build action as "EmbeddedJar" in binding project
2. JAVA: compile the .java file generated from the .aidl file as .Jar
3. add the .jar step 2 to Binding project as build action of "EmbeddedReferenceJar"
4. add the .aidl file in Xamarin.Android project (not the binding project) with build action as "AndroidInterfaceDescription"

http://blog.csdn.net/jameszhou/article/details/52474102

**Comment by carlosdelfresno** [comment]
Sorry james, but I'm trying to do the second step but I don't know how to do it... I'm not a java expert. Any other advise?

**Comment by jzhouw** [comment]
I'm not a java expert too. you can use the attached .jar which is what I got in step 2 last time



[GpService.zip](https://github.com/jamesatgithub/GPrinterDroidBinding/files/1408031/GpService.zip)
